return function()
    return {
        workspace.Towers.ToBBB.Obby:GetChildren()[3],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[5],
        workspace.Towers.ToBBB.Obby:GetChildren()[6],
        workspace.Towers.ToBBB.Obby:GetChildren()[18],
        workspace.Towers.ToBBB.Obby:GetChildren()[17],
        workspace.Towers.ToBBB.Obby:GetChildren()[24],
        workspace.Towers.ToBBB.Obby:GetChildren()[30],
        workspace.Towers.ToBBB.Obby:GetChildren()[8],
        workspace.Towers.ToBBB.Obby:GetChildren()[48],
        workspace.Towers.ToBBB.Obby:GetChildren()[141],
        workspace.Towers.ToBBB.Obby:GetChildren()[21],
        workspace.Towers.ToBBB.Obby:GetChildren()[34],
        workspace.Towers.ToBBB.Obby:GetChildren()[28],
        workspace.Towers.ToBBB.Obby:GetChildren()[32],
        workspace.Towers.ToBBB.Obby:GetChildren()[80],
        workspace.Towers.ToBBB.Obby:GetChildren()[58],
        workspace.Towers.ToBBB.Obby:GetChildren()[116],
        workspace.Towers.ToBBB.Obby:GetChildren()[57],
        workspace.Towers.ToBBB.Obby:GetChildren()[59],
        workspace.Towers.ToBBB.Obby:GetChildren()[68],
        workspace.Towers.ToBBB.Obby:GetChildren()[2],
        workspace.Towers.ToBBB.Obby:GetChildren()[41],
        workspace.Towers.ToBBB.Obby:GetChildren()[45],
        workspace.Towers.ToBBB.Obby:GetChildren()[51],
        workspace.Towers.ToBBB.Obby:GetChildren()[91],
        workspace.Towers.ToBBB.Obby:GetChildren()[93],
        workspace.Towers.ToBBB.Obby:GetChildren()[66],
        workspace.Towers.ToBBB.Obby:GetChildren()[75],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[12],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[9],
        workspace.Towers.ToBBB.Obby:GetChildren()[131],
        workspace.Towers.ToBBB.Obby:GetChildren()[169],
        workspace.Towers.ToBBB.Obby:GetChildren()[130],
        workspace.Towers.ToBBB.Obby:GetChildren()[839],
        workspace.ClientParts:GetChildren()[3]:GetChildren()[1]:GetChildren()[3],
        workspace.Towers.ToBBB.Obby:GetChildren()[144],
        workspace.ClientParts:GetChildren()[28]:GetChildren()[2],
        workspace.Towers.ToBBB.Obby:GetChildren()[143],
        workspace.Towers.ToBBB.Obby:GetChildren()[164],
        workspace.Towers.ToBBB.Obby:GetChildren()[158],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[17],
        workspace.Towers.ToBBB.Obby:GetChildren()[546],
        workspace.Towers.ToBBB.Obby.Union,
        workspace.Towers.ToBBB.Obby:GetChildren()[163],
        workspace.Towers.ToBBB.Obby:GetChildren()[161],
        workspace.Towers.ToBBB.Obby:GetChildren()[193],
        workspace.Towers.ToBBB.Obby:GetChildren()[189],
        workspace.Towers.ToBBB.Obby:GetChildren()[188],
        workspace.Towers.ToBBB.Obby:GetChildren()[190],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[18],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[21],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[20],
        workspace.Towers.ToBBB.Obby:GetChildren()[202],
        workspace.Towers.ToBBB.Obby:GetChildren()[208],
        workspace.Towers.ToBBB.Obby:GetChildren()[200],
        workspace.Towers.ToBBB.Obby:GetChildren()[211],
        workspace.Towers.ToBBB.Obby:GetChildren()[212],
        workspace.Towers.ToBBB.Obby:GetChildren()[247],
        workspace.Towers.ToBBB.Obby:GetChildren()[213],
        workspace.Towers.ToBBB.Obby:GetChildren()[197],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[27],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[23],
        workspace.Towers.ToBBB.Obby:GetChildren()[230],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[25],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[24],
        workspace.Towers.ToBBB.Obby:GetChildren()[239],
        workspace.Towers.ToBBB.Obby:GetChildren()[234],
        workspace.Towers.ToBBB.Obby:GetChildren()[257],
        workspace.Towers.ToBBB.Obby:GetChildren()[204],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[26]:GetChildren()[9],
        workspace.Towers.ToBBB.Obby:GetChildren()[252],
        workspace.Towers.ToBBB.Obby:GetChildren()[217],
        workspace.Towers.ToBBB.Obby:GetChildren()[258],
        workspace.Towers.ToBBB.Obby:GetChildren()[254],
        workspace.Towers.ToBBB.Obby:GetChildren()[261],
        workspace.Towers.ToBBB.Obby:GetChildren()[259],
        workspace.Towers.ToBBB.Obby:GetChildren()[256],
        workspace.ClientParts:GetChildren()[30]:GetChildren()[1]:GetChildren()[2],
        workspace.ClientParts:GetChildren()[2]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[4]:GetChildren()[1],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[8],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[9],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[2],
        workspace.Towers.ToBBB.Obby:GetChildren()[285],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[31],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[56],
        workspace.Towers.ToBBB.Obby:GetChildren()[302],
        workspace.Towers.ToBBB.Obby:GetChildren()[287],
        workspace.Towers.ToBBB.Obby:GetChildren()[293],
        workspace.Towers.ToBBB.Obby:GetChildren()[336],
        workspace.Towers.ToBBB.Obby:GetChildren()[27],
        workspace.ClientParts.Ball.Pushbox,
        workspace.ClientParts.Ball.Teleporter.Teleporter,
        workspace.ClientParts.Ball.Teleporter.Destination,
        workspace.Towers.ToBBB.Obby:GetChildren()[337],
        workspace.Towers.ToBBB.Obby:GetChildren()[338],
        workspace.Towers.ToBBB.Obby:GetChildren()[339],
        workspace.Towers.ToBBB.Obby:GetChildren()[341],
        workspace.ClientParts:GetChildren()[26]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[26]:GetChildren()[9],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[5]:GetChildren()[4],
        workspace.Towers.ToBBB.Obby:GetChildren()[346],
        workspace.Towers.ToBBB.Obby:GetChildren()[374],
        workspace.Towers.ToBBB.Obby:GetChildren()[365],
        workspace.ClientParts:GetChildren()[9]:GetChildren()[1],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[7],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[19],
        workspace.Towers.ToBBB.Obby:GetChildren()[388],
        workspace.Towers.ToBBB.Obby:GetChildren()[416],
        workspace.Towers.ToBBB.Obby:GetChildren()[209],
        workspace.Towers.ToBBB.Obby:GetChildren()[420],
        workspace.Towers.ToBBB.Obby:GetChildren()[404],
        workspace.Towers.ToBBB.Obby:GetChildren()[408],
        workspace.Towers.ToBBB.Obby:GetChildren()[412],
        workspace.Towers.ToBBB.Obby:GetChildren()[415],
        workspace.Towers.ToBBB.Obby:GetChildren()[435],
        workspace.Towers.ToBBB.Obby:GetChildren()[380],
        workspace.Towers.ToBBB.Obby:GetChildren()[433],
        workspace.Towers.ToBBB.Obby:GetChildren()[854],
        workspace.Towers.ToBBB.Obby:GetChildren()[434],
        workspace.Towers.ToBBB.Obby:GetChildren()[855],
        workspace.Towers.ToBBB.Obby:GetChildren()[445],
        workspace.Towers.ToBBB.Obby:GetChildren()[452],
        workspace.Towers.ToBBB.Obby:GetChildren()[462],
        workspace.Towers.ToBBB.Obby:GetChildren()[460],
        workspace.Towers.ToBBB.Obby:GetChildren()[461],
        workspace.Towers.ToBBB.Obby:GetChildren()[455],
        workspace.Towers.ToBBB.Obby:GetChildren()[463],
        workspace.Towers.ToBBB.Obby:GetChildren()[449],
        workspace.Towers.ToBBB.Obby:GetChildren()[447],
        workspace.Towers.ToBBB.Obby:GetChildren()[378],
        workspace.ClientParts:GetChildren()[18]:GetChildren()[1],
        workspace.Towers.ToBBB.Obby:GetChildren()[431],
        workspace.Towers.ToBBB.Obby:GetChildren()[539],
        workspace.Towers.ToBBB.Obby:GetChildren()[489],
        workspace.Towers.ToBBB.Obby:GetChildren()[491],
        workspace.Towers.ToBBB.Obby:GetChildren()[330],
        workspace.Towers.ToBBB.Obby:GetChildren()[500],
        workspace.Towers.ToBBB.Obby:GetChildren()[576],
        workspace.Towers.ToBBB.Obby:GetChildren()[510],
        workspace.Towers.ToBBB.Obby:GetChildren()[506],
        workspace.Towers.ToBBB.Obby:GetChildren()[513],
        workspace.Towers.ToBBB.Obby:GetChildren()[511],
        workspace.Towers.ToBBB.Obby:GetChildren()[514],
        workspace.Towers.ToBBB.Obby:GetChildren()[573],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[42],
        workspace.Towers.ToBBB.Obby:GetChildren()[533],
        workspace.Towers.ToBBB.Obby:GetChildren()[545],
        workspace.Towers.ToBBB.Obby:GetChildren()[542],
        workspace.Towers.ToBBB.Obby:GetChildren()[547],
        workspace.Towers.ToBBB.Obby:GetChildren()[541],
        workspace.Towers.ToBBB.Obby:GetChildren()[561],
        workspace.Towers.ToBBB.Obby:GetChildren()[571],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[76]:GetChildren()[11],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[78]:GetChildren()[5],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[77]:GetChildren()[3],
        workspace.Towers.ToBBB.Obby:GetChildren()[558],
        workspace.Towers.ToBBB.Obby:GetChildren()[592],
        workspace.Towers.ToBBB.Obby:GetChildren()[590],
        workspace.Towers.ToBBB.Obby:GetChildren()[9],
        workspace.Towers.ToBBB.Obby:GetChildren()[603],
        workspace.Towers.ToBBB.Obby:GetChildren()[597],
        workspace.Towers.ToBBB.Obby:GetChildren()[599],
        workspace.Towers.ToBBB.Obby:GetChildren()[585],
        workspace.Towers.ToBBB.Obby:GetChildren()[414],
        workspace.Towers.ToBBB.Obby:GetChildren()[624],
        workspace.Towers.ToBBB.Obby:GetChildren()[596],
        workspace.Towers.ToBBB.Obby:GetChildren()[551],
        workspace.ClientParts:GetChildren()[1]:GetChildren()[2],
        workspace.Towers.ToBBB.Obby:GetChildren()[631],
        workspace.Towers.ToBBB.Obby:GetChildren()[629],
        workspace.Towers.ToBBB.Obby:GetChildren()[637],
        workspace.Towers.ToBBB.Obby:GetChildren()[639],
        workspace.Towers.ToBBB.Obby:GetChildren()[638],
        workspace.Towers.ToBBB.Obby:GetChildren()[801],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[95],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[64],
        workspace.Towers.ToBBB.Obby:GetChildren()[805],
        workspace.Towers.ToBBB.Obby:GetChildren()[809],
        workspace.Towers.ToBBB.Obby:GetChildren()[819],
        workspace.Towers.ToBBB.Obby:GetChildren()[815],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[47]:GetChildren()[6],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[47]:GetChildren()[5],
        workspace.Towers.ToBBB.Obby:GetChildren()[523],
        workspace.Towers.ToBBB.Obby:GetChildren()[827],
        workspace.Towers.ToBBB.Obby:GetChildren()[836],
        workspace.Towers.ToBBB.Obby:GetChildren()[821],
        workspace.Towers.ToBBB.Obby:GetChildren()[834],
        workspace.Towers.ToBBB.Obby:GetChildren()[812],
        workspace.Towers.ToBBB.Obby:GetChildren()[798],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[48],
        workspace.Towers.ToBBB.Obby:GetChildren()[438],
        workspace.ClientParts.Elevator,
        workspace.Towers.ToBBB.Obby:GetChildren()[646],
        workspace.Towers.ToBBB.Obby:GetChildren()[437],
        workspace.Towers.ToBBB.Obby:GetChildren()[436],
        workspace.Towers.ToBBB.Obby:GetChildren()[519],
        workspace.Towers.ToBBB.Obby:GetChildren()[846],
        workspace.ClientParts["Beat Blocks"]["2x"]:GetChildren()[59],
        workspace.Towers.ToBBB.Obby:GetChildren()[649],
        workspace.ClientParts:GetChildren()[11]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[11]:GetChildren()[2],
        workspace.Towers.ToBBB.Obby:GetChildren()[653],
        workspace.Towers.ToBBB.Obby:GetChildren()[586],
        workspace.Towers.ToBBB.Obby:GetChildren()[657],
        workspace.Towers.ToBBB.Obby:GetChildren()[664],
        workspace.Towers.ToBBB.Obby:GetChildren()[677],
        workspace.Towers.ToBBB.Obby:GetChildren()[667],
        workspace.Towers.ToBBB.Obby:GetChildren()[669],
        workspace.Towers.ToBBB.Obby:GetChildren()[679],
        workspace.ClientParts.Morphers:GetChildren()[1]:GetChildren()[4]:GetChildren()[1],
        workspace.ClientParts.Morphers:GetChildren()[1]:GetChildren()[5]:GetChildren()[6],
        workspace.Towers.ToBBB.Obby:GetChildren()[706],
        workspace.Towers.ToBBB.Obby:GetChildren()[705],
        workspace.Towers.ToBBB.Obby:GetChildren()[688],
        workspace.Towers.ToBBB.Obby:GetChildren()[692],
        workspace.Towers.ToBBB.Obby:GetChildren()[698],
        workspace.Towers.ToBBB.Obby:GetChildren()[700],
        workspace.Towers.ToBBB.Obby:GetChildren()[790],
        workspace.Towers.ToBBB.Obby:GetChildren()[707],
        workspace.Towers.ToBBB.Obby:GetChildren()[697],
        workspace.ClientParts.Morphers:GetChildren()[1]:GetChildren()[7]:GetChildren()[1],
        workspace.Towers.ToBBB.Obby:GetChildren()[708],
        workspace.Towers.ToBBB.Obby:GetChildren()[773],
        workspace.Towers.ToBBB.Obby:GetChildren()[711],
        workspace.Towers.ToBBB.Obby:GetChildren()[721],
        workspace.Towers.ToBBB.Obby:GetChildren()[720],
        workspace.Towers.ToBBB.Obby:GetChildren()[722],
        workspace.Towers.ToBBB.Obby:GetChildren()[719],
        workspace.Towers.ToBBB.Obby:GetChildren()[789],
        workspace.Towers.ToBBB.Obby:GetChildren()[788],
        workspace.ClientParts.Morphers:GetChildren()[1]:GetChildren()[8]:GetChildren()[1],
        workspace.Towers.ToBBB.Obby:GetChildren()[726],
        workspace.Towers.ToBBB.Obby:GetChildren()[727],
        workspace.Towers.ToBBB.Obby:GetChildren()[745],
        workspace.Towers.ToBBB.Obby:GetChildren()[746],
        workspace.Towers.ToBBB.Obby:GetChildren()[748],
        workspace.Towers.ToBBB.Obby:GetChildren()[736],
        workspace.Towers.ToBBB.Obby:GetChildren()[786],
        workspace.Towers.ToBBB.Obby:GetChildren()[793],
        workspace.Towers.ToBBB.Obby:GetChildren()[753],
        workspace.Towers.ToBBB.Obby:GetChildren()[763],
        workspace.Towers.ToBBB.Obby:GetChildren()[764],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[10],
        workspace.ClientParts:GetChildren()[21]:GetChildren()[1],
        workspace.ClientParts.Morphers:GetChildren()[1]:GetChildren()[5]:GetChildren()[15],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[3],
        workspace.Towers.ToBBB.Obby:GetChildren()[650],
        workspace.ClientParts:GetChildren()[19]:GetChildren()[1]:GetChildren()[2],
        workspace.Towers.ToBBB.WinPad
    }
end
